# Generated by Django 4.2.1 on 2023-08-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_age', models.IntegerField()),
            ],
        ),
    ]
